language: python
python:
  - "3.5"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install mypy
script:
  - mypy challonge
  - mypy tests.py
  - coverage run --source=challonge tests.py -v
after_success:
  - coveralls
