language: python
python:
  - "3.5"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python ./tests.py
  - coverage run --source=challonge tests.py
after_success:
  - coveralls